### ISSUE TITLE
Can you share build WASM projects?

### ISSUE THREAD

**Issue by frank-pian** [gkv311/occt-draw#1]
CMakeList or Dockerfile? I want to try to build this project. Thank you for your help.

**Comment by gkv311** [comment]
`DRAWEXE.wasm` is built directly out of OCCT source code.

I'm using development snapshots out of git repository - the latest build corresponds to [IR-2021-12-17](https://git.dev.opencascade.org/gitweb/?p=occt.git;a=shortlog;h=refs/heads/IR-2021-12-17) branch (see comment in the git; you may also use command `dversion` to see build details in DRAWEXE).

[adm/scripts/wasm_build.bat](https://git.dev.opencascade.org/gitweb/?p=occt.git;a=blob;f=adm/scripts/wasm_build.bat) is used for configuring build and calling CMake (`set "BUILD_Draw=ON"` should be set in `wasm_custom.bat` to enable DRAWEXE). For this project, you'll have to make two builds with and without pthreads (`USE_PTHREADS` in `wasm_custom.bat`) and put build artifacts into  `wasm32-pthread` and ` wasm32` folders. Or make a single build and keep one folder empty. I'm also using a small script extension patching `Standard_Version.hxx` to put git branch name into `dversion` output.

The `wasm_build.sh` lies nearby in the same folder [adm/scripts/] if you would like to put it into Docker, but it should be extended for that purpose (compare CMake configure flags with `wasm_build.bat`).

Tcl 8.6.11 is built with a small WASM compatibility [patches](https://github.com/gkv311/tcl/commit/fe03c8dcedbe071377083da640239321328a7cfa) - currently from [this repository](https://github.com/gkv311/tcl), see also an auxiliary building script there. The workaround for `getpwuid()` might be unneeded for the latest Emscripten release as I've seen that they fixed this problem recently in their [ChangeLog](https://emscripten.org/docs/introducing_emscripten/release_notes.html);
> 2.0.32 - 10/19/2021
> the `getpwnam` family of functions were changed to return an  error rather than throw a JavaScript exception

FreeType (`USE_FREETYPE=ON`) and Draco (`USE_DRACO=ON`) are built out of official source code unmodified. RapidJson (`USE_RAPIDJSON=ON`) could be taken from official release as well - it is a header-only library that is no need to be built in advance.

**Comment by frank-pian** [comment]
I tried compiling it on Ubuntu. But I encountered an incomprehensible error.
This is my rewrite of wasm_build.sh
[wasm_build.zip](https://github.com/gkv311/occt-draw/files/8022132/wasm_build.zip)

```
[100%] Building CXX object src/TKQADraw/CMakeFiles/TKQADraw.dir/__/QANCollection/QANCollection_Common.cxx.o
[100%] Building CXX object src/TKQADraw/CMakeFiles/TKQADraw.dir/__/QANCollection/QANCollection_Perf.cxx.o
[100%] Building CXX object src/TKQADraw/CMakeFiles/TKQADraw.dir/__/QANCollection/QANCollection_Stl.cxx.o
[100%] Building CXX object src/TKQADraw/CMakeFiles/TKQADraw.dir/__/QANCollection/QANCollection_Test.cxx.o
[100%] Building CXX object src/DRAWEXE/CMakeFiles/DRAWEXE.dir/DRAWEXE.cxx.o
[100%] Linking CXX executable ../../lin32/clang/bin/DRAWEXE.js
[100%] Linking CXX static library ../../lin32/clang/lib/libTKQADraw.a
[100%] Built target TKQADraw
Problem during make operation
~/project/opencascade/adm/scripts
```

```
Start building OCCT for wasm
em++: warning: linker flag ignored during compilation: '--bind' [-Wunused-command-line-argument]
wasm-ld: error: unknown file type: ftbase.c.o
em++: error: '/home/frankpian/project/emsdk/upstream/bin/wasm-ld -o ../../lin32/clang/bin/DRAWEXE.js-7.7.wasm CMakeFiles/DRAWEXE.dir/DRAWEXE.cxx.o -L/home/frankpian/project/opencascade/adm/scripts/../../../3rdparty/tcl-wasm32/lib -L/home/frankpian/project/3rdparty/freetype-2.7.1-wasm/lib -L/home/frankpian/project/3rdparty/draco-1.5.0-wasm/lib ../../lin32/clang/lib/libTKTopTest.a ../../lin32/clang/lib/libTKDCAF.a ../../lin32/clang/lib/libTKXSDRAW.a ../../lin32/clang/lib/libTKXDEDRAW.a ../../lin32/clang/lib/libTKOpenGlesTest.a ../../lin32/clang/lib/libTKViewerTest.a ../../lin32/clang/lib/libTKDraw.a ../../lin32/clang/lib/libTKMeshVS.a ../../lin32/clang/lib/libTKXDESTEP.a ../../lin32/clang/lib/libTKSTEP.a ../../lin32/clang/lib/libTKSTEPAttr.a ../../lin32/clang/lib/libTKSTEP209.a ../../lin32/clang/lib/libTKSTEPBase.a ../../lin32/clang/lib/libTKXDEIGES.a ../../lin32/clang/lib/libTKIGES.a ../../lin32/clang/lib/libTKXSBase.a ../../lin32/clang/lib/libTKVRML.a ../../lin32/clang/lib/libTKSTL.a ../../lin32/clang/lib/libTKRWMesh.a ../../lin32/clang/lib/libTKBinXCAF.a ../../lin32/clang/lib/libTKXmlXCAF.a ../../lin32/clang/lib/libTKBin.a ../../lin32/clang/lib/libTKXml.a ../../lin32/clang/lib/libTKXmlL.a ../../lin32/clang/lib/libTKBinL.a ../../lin32/clang/lib/libTKOpenGles.a ../../lin32/clang/lib/libTKXCAF.a ../../lin32/clang/lib/libTKVCAF.a ../../lin32/clang/lib/libTKStd.a ../../lin32/clang/lib/libTKCAF.a ../../lin32/clang/lib/libTKV3d.a ../../lin32/clang/lib/libTKHLR.a ../../lin32/clang/lib/libTKMesh.a ../../lin32/clang/lib/libTKService.a ../../lin32/clang/lib/libTKOffset.a ../../lin32/clang/lib/libTKFillet.a ../../lin32/clang/lib/libTKFeat.a ../../lin32/clang/lib/libTKBool.a ../../lin32/clang/lib/libTKBO.a ../../lin32/clang/lib/libTKShHealing.a ../../lin32/clang/lib/libTKPrim.a ../../lin32/clang/lib/libTKTopAlgo.a ../../lin32/clang/lib/libTKGeomAlgo.a ../../lin32/clang/lib/libTKBRep.a ../../lin32/clang/lib/libTKGeomBase.a ../../lin32/clang/lib/libTKG3d.a ../../lin32/clang/lib/libTKG2d.a ../../lin32/clang/lib/libTKMath.a ../../lin32/clang/lib/libTKStdL.a ../../lin32/clang/lib/libTKLCAF.a ../../lin32/clang/lib/libTKCDF.a ../../lin32/clang/lib/libTKernel.a ../../../../adm/scripts/../../../3rdparty/tcl-wasm32/lib/libtcl.a /home/frankpian/project/3rdparty/freetype-2.7.1-wasm/lib/libfreetype.a ../../../../adm/scripts/../../../3rdparty/draco-1.5.0-wasm/lib/libdraco.a /home/frankpian/project/3rdparty/draco-1.5.0-wasm/lib/libdraco.a -L/home/frankpian/project/emsdk/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten --whole-archive -lembind-rtti --no-whole-archive -lGL-webgl2 -lal -lhtml5 -lstubs -lc -lcompiler_rt -lc++ -lc++abi -ldlmalloc -lc_rt -lsockets -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --import-undefined --strip-debug --export-if-defined=main --export-if-defined=__start_em_asm --export-if-defined=__stop_em_asm --export=stackSave --export=stackRestore --export=stackAlloc --export=__wasm_call_ctors --export=__errno_location --export=malloc --export=free --export=__cxa_is_pointer_type --export=__cxa_can_catch --export=setThrew --export=saveSetjmp --export=emscripten_main_thread_process_queued_calls --export=_get_tzname --export=_get_daylight --export=_get_timezone --export=__dl_seterr --export=htons --export=memalign --export=ntohs --export=htonl --export-table -z stack-size=5242880 --initial-memory=16777216 --no-entry --max-memory=2147483648 --global-base=1024' failed (returned 1)
make[2]: *** [src/DRAWEXE/CMakeFiles/DRAWEXE.dir/build.make:142：lin32/clang/bin/DRAWEXE.js-7.7.0] 错误 1
make[1]: *** [CMakeFiles/Makefile2:2929：src/DRAWEXE/CMakeFiles/DRAWEXE.dir/all] 错误 2
make: *** [Makefile:130：all] 错误 2
```

Is the reason for this problem because the ftbase.c.o file cannot be found ?

**Comment by gkv311** [comment]
> Is the reason for this problem because the ftbase.c.o file cannot be found ?

It doesn't say that it cannot find this file, it says `unknown file type: ftbase.c.o`.
Don't know what that could mean. I guess `ftbase` comes from `FreeType` library, so maybe there is some issue in it.

**Comment by frank-pian** [comment]
> > Is the reason for this problem because the ftbase.c.o file cannot be found ?
> 
> It doesn't say that it cannot find this file, it says `unknown file type: ftbase.c.o`. Don't know what that could mean. I guess `ftbase` comes from `FreeType` library, so maybe there is some issue in it.

I found out why
Both Freetype and Draco need to be built with emsdk
I use the EmSDK Build Draco directory like this
```
export EMSCRIPTEN=~/project/emsdk/upstream/emscripten
cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE:FILEPATH="${EMSDK}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake" -DDRACO_WASM=ON -DCMAKE_INSTALL_PREFIX=~/project/3rdparty/draco-1.5.0-wasm ..
make
```
![捕获](https://user-images.githubusercontent.com/8214804/152972647-3bb86064-5f37-456a-84cf-2bdc0d8d73cb.PNG)
No libdraco.a file and "make install" .
So what's different about Build Draco ?

**Comment by gkv311** [comment]
@frank-pian I've put some scripts that could be useful for writing Docker scripts into **3rdparty** folder:
https://github.com/gkv311/occt-draw/tree/master/3rdparty

**Comment by gkv311** [comment]
Draco 1.4.1 building options looked like this in my environment:
```
if ["%toCMake%"] == ["1"] (
  cmake -G "MinGW Makefiles" ^
 -D CMAKE_TOOLCHAIN_FILE:FILEPATH="%aToolchain%" ^
 -D CMAKE_BUILD_TYPE:STRING="Release" ^
 -D CMAKE_INSTALL_PREFIX:PATH="%aDestDir%" ^
 -D BUILD_LIBRARY_TYPE:STRING="Static" ^
 -D DRACO_WASM:BOOL="ON" ^
 -D DRACO_JS_GLUE:BOOL="OFF" ^
 "%aDracoSrc%"
```

**Comment by frank-pian** [comment]
thank you very much for you help!
