### ISSUE TITLE
Delete prompt() box

### ISSUE THREAD

**Issue by frank-pian** [gkv311/occt-draw#2]
I import drawexe.js in the React project. The prompt() input box always pops up. 
Where is this code? I can't find it in the OCCT source code. I want to delete this dialog box.
Thanks

**Comment by gkv311** [comment]
I'm not familiar with React, and don't how you load drawexe.js there.

Tcl shell by default expects input on standard stream, which is emulated by Emscripten by dialog box.
`DRAWEXE.js` uses `Module.noExitRuntime` flag to disable this default behavior, see `DrawTerm` class in [`drawxterm.js`](https://github.com/gkv311/occt-draw/blob/master/js/drawxterm.js):
>    // tell Emscripten and Draw Harness to not use std::cin for commands input
>    this.noExitRuntime = true;
